version: "3"

services:
  db:
    image: mongo:3.2
    ports:
      - 27017
  app:
    image: catalyst
    stdin_open: true
    tty: true
    links:
      - db
    build: 
        context: .
        dockerfile: Dockerfile
    depends_on:
      - db
    command: /bin/bash
    ports:
      - 5000:80
